In [117]:
# Student Name: Ahmad Sharif
# Student ID : K436765
# Exercise 03
# Date: 18 September 2022

In [89]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from random import random
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier


#Cifar-10 KNN code
import sys 
sys.executable
import numpy as np
import os
#pickle for serialisation and de-serialisation
import pickle
import matplotlib.pyplot as plt
#For embedded Visualisation 
#from vega3 import VegaLite
#API for display tools
from IPython.display import clear_output


## Importing Datsets

In [90]:
rel_path = "data/cifar-10-batches-py/"


In [91]:
def unpickle(file):
    with open(file, 'rb') as f:
        dict = pickle.load(f, encoding="latin1")
    return dict


In [92]:
X = unpickle(rel_path + 'data_batch_1')
img_data = X['data']
img_label_orig = img_label = X['labels']
img_label = np.array(img_label).reshape(-1, 1)
#Now that our data and labels are loaded lets check their presence 
print(img_data)
print('shape', img_data.shape)

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 71  60  74 ...  68  69  68]
 [250 254 211 ... 215 255 254]
 [ 62  61  60 ... 130 130 131]]
shape (10000, 3072)


In [93]:
test_X = unpickle(rel_path + 'test_batch');
test_data = test_X['data']
test_label = test_X['labels']
test_label = np.array(test_label).reshape(-1, 1)
#Let's check the Test dataset 
print(test_data)
print('shape', test_data.shape)

[[158 159 165 ... 124 129 110]
 [235 231 232 ... 178 191 199]
 [158 158 139 ...   8   3   7]
 ...
 [ 20  19  15 ...  50  53  47]
 [ 25  15  23 ...  80  81  80]
 [ 73  98  99 ...  94  58  26]]
shape (10000, 3072)


In [102]:
sample_img_data = img_data[10:20, :]
print(sample_img_data)
print('shape', sample_img_data.shape)
# We, obtain 10*3072 data matrice 
#The dataset has image names in the batches.meta file, lets get the file to display the image
batch = unpickle(rel_path + 'batches.meta');
meta = batch['label_names']
print(meta)

[[ 53  54  56 ...  39  46  41]
 [142 172 176 ... 105 106 111]
 [164 162 162 ... 108 107 100]
 ...
 [110 142 151 ...  60  60  62]
 [197 198 201 ...  61  63  57]
 [ 23  47  52 ... 184 183 186]]
shape (10, 3072)
['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


In [99]:
from PIL import Image
import numpy as np
from IPython.display import display

def default_label_fn(i, original):
    return original


def show_img(img_arr, label_arr, meta, index, label_fn=default_label_fn):
    """
        Given a numpy array of image from CIFAR-10 labels this method transform the data so that PIL can read and show
        the image.
        Check here how CIFAR encodes the image http://www.cs.toronto.edu/~kriz/cifar.html
    """
    
    one_img = img_arr[index,:]
    # Assume image size is 32 x 32. First 1024 px is r, next 1024 px is g, last 1024 px is b from the (r,g b) channel
    r = one_img[:1024].reshape(32, 32)
    g = one_img[1024:2048].reshape(32, 32)
    b = one_img[2048:]. reshape(32, 32)
    rgb = np.dstack([r, g, b])
    img = Image.fromarray(np.array(rgb), 'RGB')
    display(img)
    print(label_fn(index, meta[label_arr[index][0]]))
    

for i in range(0, 10):
    # show_img(sample_img_data, img_label, meta, i)
    pass

In [128]:
from sklearn.neighbors import KNeighborsClassifier
neighbors = KNeighborsClassifier(n_neighbors=3, algorithm='brute').fit(img_data, img_label_orig)
YPred_soa = neighbors.predict(sample_img_data)


def accuracy(meta, test_label, x):
    print(meta meta[YPred_soa[pred]])
    
# Exercise 2
def class_acc(pred, gt):
    _pred = meta[YPred_soa[pred]]
    return gt + '::' + meta[YPred_soa[pred]]

for x in range(0, len(YPred_soa)):
    accuracy(meta, test_label, x)
    show_img(sample_img_data, test_label, meta, x, label_fn=class_acc)


TypeError: can only concatenate list (not "str") to list